// react-ui/src/components/UserModal.js
import React                                                                                    from 'react';
import PropTypes                                                                                from 'prop-types';
import {Button, Col, Form, FormGroup, Input, Label, Modal, ModalBody, ModalFooter, ModalHeader} from 'reactstrap';
import {Formik}                                                                                 from 'formik';
import * as Yup                                                                                 from 'yup';

const UserModal = (props) => {
  let modalTitle = '';
  let buttonText = '';

  switch (props.mode) {
    case 'Add':
      modalTitle = 'Add User';
      buttonText = 'Save User';
      break;
    case 'Edit':
      modalTitle = 'Edit User';
      buttonText = 'Save User';
      break;
    case 'Delete':
      modalTitle = 'Delete User';
      buttonText = 'Delete User';
      break;
    default:
      break;
  }

  return (
      <Formik
          initialValues={{
            username: props.user.username ? props.user.username : '',
            accountExpired: props.user.accountNonExpired !== undefined ? !props.user.accountNonExpired : false,
            accountLocked: props.user.accountNonLocked !== undefined ? !props.user.accountNonLocked : false,
            credentialsExpired: props.user.credentialsNonExpired !== undefined ? !props.user.credentialsNonExpired : false,
            enabled: props.user.enabled !== undefined ? props.user.enabled : true,
            isUser: true,
            isAdmin: props.user.roles ? props.user.roles.filter(role => role.name === 'ROLE_ADMIN').length === 1 : false
          }}
          enableReinitialize={true}
          validationSchema={Yup.object().shape({
            username: Yup.string().required('Required'),
            accountExpired: Yup.bool(),
            accountLocked: Yup.bool(),
            credentialsExpired: Yup.bool(),
            enabled: Yup.bool(),
            isUser: Yup.bool(),
            isAdmin: Yup.bool()
          })}
          isInitialValid={(formikBag) => {
            return formikBag.validationSchema.isValidSync(formikBag.initialValues);
          }}
          onSubmit={async (values, actions) => {
            let roles = [{id: 1, name: 'ROLE_USER'}];
            if (values.isAdmin) {
              roles.push({id: 2, name: 'ROLE_ADMIN'});
            }
            await props.submitCallback({
              username: values.username,
              accountNonExpired: !values.accountExpired,
              accountNonLocked: !values.accountLocked,
              credentialsNonExpired: !values.credentialsExpired,
              enabled: values.enabled,
              roles: roles
            });
            actions.setSubmitting(false);
          }}
      >
        {(formikProps) => (
            <Modal isOpen={props.open} toggle={props.cancelCallback}>
              <ModalHeader toggle={props.cancelCallback}>{modalTitle}</ModalHeader>
              <Form onSubmit={e => e.preventDefault()}>
                <ModalBody>
                  {props.errorMessage &&
                  <Label className="text-danger font-weight-bold">Error: {props.errorMessage}</Label>}
                  {props.mode === 'Delete' &&
                  <p>Are you sure you want to delete {props.user.username}?</p>
                  }
                  {props.mode !== 'Delete' &&
                  <React.Fragment>
                    <FormGroup row>
                      <Label sm={4}>Username</Label>
                      <Col sm={8}>
                        <Input
                            name="username"
                            placeholder="Username"
                            onChange={formikProps.handleChange}
                            onBlur={formikProps.handleBlur}
                            value={formikProps.values.username}
                            invalid={formikProps.touched.username && formikProps.errors.username}
                            disabled={props.mode === 'Edit'}/>
                      </Col>
                    </FormGroup>
                    <FormGroup row>
                      <Label sm={4} className="pt-0">Account Status</Label>
                      <Col sm={8}>
                        <FormGroup check>
                          <Label check>
                            <Input
                                type="checkbox"
                                name="accountExpired"
                                onChange={formikProps.handleChange}
                                onBlur={formikProps.handleBlur}
                                checked={formikProps.values.accountExpired}/>Expired
                          </Label>
                        </FormGroup>
                        <FormGroup check>
                          <Label check>
                            <Input
                                type="checkbox"
                                name="accountLocked"
                                onChange={formikProps.handleChange}
                                onBlur={formikProps.handleBlur}
                                checked={formikProps.values.accountLocked}/>Locked
                          </Label>
                        </FormGroup>
                        <FormGroup check>
                          <Label check>
                            <Input
                                type="checkbox"
                                name="credentialsExpired"
                                onChange={formikProps.handleChange}
                                onBlur={formikProps.handleBlur}
                                checked={formikProps.values.credentialsExpired}/>Credentials Expired
                          </Label>
                        </FormGroup>
                        <FormGroup check>
                          <Label check>
                            <Input
                                type="checkbox"
                                name="enabled"
                                onChange={formikProps.handleChange}
                                onBlur={formikProps.handleBlur}
                                checked={formikProps.values.enabled}/>Enabled
                          </Label>
                        </FormGroup>
                      </Col>
                    </FormGroup>
                    <FormGroup row>
                      <Label sm={4} className="pt-0">Roles</Label>
                      <Col sm={8}>
                        <FormGroup check>
                          <Label check>
                            <Input
                                type="checkbox"
                                name="isUser"
                                onChange={formikProps.handleChange}
                                onBlur={formikProps.handleBlur}
                                disabled={true}
                                checked={true}/>User
                          </Label>
                        </FormGroup>
                        <FormGroup check>
                          <Label check>
                            <Input
                                type="checkbox"
                                name="isAdmin"
                                onChange={formikProps.handleChange}
                                onBlur={formikProps.handleBlur}
                                checked={formikProps.values.isAdmin}/>Admin
                          </Label>
                        </FormGroup>
                      </Col>
                    </FormGroup>
                  </React.Fragment>
                  }
                </ModalBody>
                <ModalFooter>
                  <Button
                      color="primary"
                      onClick={formikProps.handleSubmit}
                      disabled={!formikProps.isValid || formikProps.isSubmitting}>
                    {buttonText}</Button>
                  <Button
                      color="primary"
                      onClick={props.cancelCallback}>
                    Cancel
                  </Button>
                </ModalFooter>
              </Form>
            </Modal>
        )}
      </Formik>
  );
};

UserModal.propTypes = {
  open: PropTypes.bool.isRequired,
  mode: PropTypes.oneOf(['Add', 'Edit', 'Delete']).isRequired,
  user: PropTypes.object.isRequired,
  errorMessage: PropTypes.string,
  submitCallback: PropTypes.func.isRequired,
  cancelCallback: PropTypes.func.isRequired
};

export default UserModal;

// ui/src/app/features/user/user-list/user-modal/user-modal.component.ts
import {HttpErrorResponse} from '@angular/common/http';
import {Component, Input, OnInit} from '@angular/core';
import {FormArray, FormControl, FormGroup, Validators} from '@angular/forms';
import {NgbActiveModal} from '@ng-bootstrap/ng-bootstrap';
import {User} from '@rest-services/api/model/user.model';
import {UserService} from '@rest-services/api/user/user.service';

@Component({
  selector: 'app-user-modal',
  templateUrl: './user-modal.component.html',
  styleUrls: ['./user-modal.component.scss']
})
export class UserModalComponent implements OnInit {
  @Input() mode: string;
  @Input() user: User;
  title: string;
  actionButtonText: string;
  actionInProgress = false;
  hideErrorMessage = true;
  errorMessage: string;
  userForm: FormGroup;

  roleTypes = [{
    displayName: 'User',
    value: 'ROLE_USER'
  }, {
    displayName: 'Admin',
    value: 'ROLE_ADMIN'
  }];

  constructor(public activeModal: NgbActiveModal,
              private userService: UserService) {
  }

  ngOnInit() {
    switch (this.mode) {
      case 'add':
        this.title = 'Add User';
        this.actionButtonText = 'Save User';
        break;
      case 'edit':
        this.title = 'Edit User';
        this.actionButtonText = 'Save User';
        break;
      case 'delete':
        this.title = 'Confirm Delete';
        this.actionButtonText = 'Delete User';
        break;
    }

    this.userForm = new FormGroup({
      username: new FormControl(this.user.username, [Validators.required]),
      accountExpired: new FormControl(!this.user.accountNonExpired),
      accountLocked: new FormControl(!this.user.accountNonLocked),
      credentialsExpired: new FormControl(!this.user.credentialsNonExpired),
      enabled: new FormControl(this.user.enabled),
      roles: new FormArray([
        new FormControl({
          value: this.user.roles.filter(role => role.name === 'ROLE_USER').length === 1,
          disabled: true
        }),
        new FormControl(this.user.roles.filter(role => role.name === 'ROLE_ADMIN').length === 1)
      ])
    });
  }

  handleActionButtonClick(user: User) {
    this.actionInProgress = true;
    switch (this.mode) {
      case 'add':
      // fall through is on purpose
      case 'edit':
        this.actionButtonText = 'Saving User';
        this.actionInProgress = true;
        const roles: [{ id: number, name: string }] = [{id: 1, name: 'ROLE_USER'}];
        // Offset starts at 0 because User checkbox is disabled and that value does not get included in the form
        if (this.userForm.value.roles[0]) {
          roles.push({id: 2, name: 'ROLE_ADMIN'});
        }

        const userToSave: User = {
          id: this.user.id,
          username: this.userForm.value.username,
          accountNonExpired: !this.userForm.value.accountExpired,
          accountNonLocked: !this.userForm.value.accountLocked,
          credentialsNonExpired: !this.userForm.value.credentialsExpired,
          enabled: this.userForm.value.enabled,
          roles: roles
        };

        this.userService.saveUser(userToSave).subscribe(
          (savedUser) => {
            this.activeModal.close(savedUser);
          },
          (response: HttpErrorResponse) => {
            this.actionButtonText = 'Save User';
            this.actionInProgress = false;
            this.hideErrorMessage = false;
            if (response.status === 0) {
              this.errorMessage = 'Unable to save ' + this.user.username + '.  Please try again later.';
            } else {
              this.errorMessage = response.error.message;
            }
          }
        );
        break;
      case 'delete':
        this.actionButtonText = 'Deleting User';
        this.actionInProgress = true;
        this.userService.deleteUser(user).subscribe(
          () => {
            this.activeModal.close();
          },
          () => {
            this.actionButtonText = 'Delete User';
            this.actionInProgress = false;
            this.hideErrorMessage = false;
            this.errorMessage = 'Unable to delete ' + user.username + '.  Please try again later.';
          });
        break;
    }
  }

}

<div class="modal-header">
  <h4 class="modal-title">{{title}}</h4>
  <button type="button" class="close" aria-label="Close" (click)="activeModal.dismiss('Cross click')">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <label class="col-form-label error" [hidden]="hideErrorMessage">Error: {{errorMessage}}</label>
  <form novalidate *ngIf="mode === 'add' || mode === 'edit'" [formGroup]="userForm" (ngSubmit)="handleActionButtonClick(user)">
    <div class="form-group row">
      <label class="col-sm-4 col-form-label">Username</label>
      <div class="col-sm-8">
        <input class="form-control" placeholder="Username" formControlName="username">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-form-label col-sm-4 pt-0">Account Status</label>
      <div class="col-sm-8">
        <div class="form-check">
          <label class="form-check-label">
            <input class="form-check-input" type="checkbox" formControlName="accountExpired">Expired
          </label>
        </div>
        <div class="form-check">
          <label class="form-check-label">
            <input class="form-check-input" type="checkbox" formControlName="accountLocked">Locked
          </label>
        </div>
        <div class="form-check">
          <label class="form-check-label">
            <input class="form-check-input" type="checkbox" formControlName="credentialsExpired">Credentials Expired
          </label>
        </div>
        <div class="form-check">
          <label class="form-check-label">
            <input class="form-check-input" type="checkbox" formControlName="enabled">Enabled
          </label>
        </div>
      </div>
    </div>
    <div class="form-group row" formArrayName="authorities">
      <label class="col-form-label col-sm-4 pt-0">Roles</label>
      <div class="col-sm-8">
        <div class="form-check" *ngFor="let authority of userForm.get('authorities')['controls']; let i = index">
          <label class="form-check-label">
            <input class="form-check-input" type="checkbox" [formControlName]="i">{{authorityTypes[i].displayName}}
          </label>
        </div>
      </div>
    </div>
  </form>
  <p *ngIf="mode=='delete'">Are you sure you want to delete {{user.username}}?</p>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-primary" [disabled]="actionInProgress || !userForm.valid" (click)="handleActionButtonClick(user)">{{actionButtonText}}</button>
  <button type="button" class="btn btn-primary" [disabled]="actionInProgress" (click)="activeModal.dismiss('Cancel click')">Cancel</button>
</div>
