// angular-ui/src/app/features/user/user-list/user-list.component.ts
import {Component, OnInit} from '@angular/core';
import {UserSessionService} from '@core/services/user-session.service';
import {UserModalComponent} from '@features/user/user-list/user-modal/user-modal.component';
import {NgbModal} from '@ng-bootstrap/ng-bootstrap';
import {User} from '@rest-services/api/model/user.model';
import {UserService} from '@rest-services/api/user/user.service';

@Component({
  selector: 'app-user-list',
  templateUrl: './user-list.component.html',
  styleUrls: ['./user-list.component.scss']
})
export class UserListComponent implements OnInit {
  users: User[] = [];

  constructor(public userSessionService: UserSessionService,
              private userService: UserService,
              private modalService: NgbModal) {
  }

  ngOnInit() {
    this.userService.users().subscribe(
      users => {
        this.users = users;
      }
    );
  }

  handleAddClick() {
    const modalRef = this.modalService.open(UserModalComponent);
    modalRef.componentInstance.mode = 'add';
    modalRef.componentInstance.user = {
      username: null,
      accountNonExpired: true,
      accountNonLocked: true,
      credentialsNonExpired: true,
      enabled: true,
      roles: [{id: 1, name: 'ROLE_USER'}]
    };
    modalRef.result.then(
      (savedUser) => {
        this.users.push(savedUser);
      },
      () => {
      }
    );
  }

  handleEditClick(user: User) {
    const modalRef = this.modalService.open(UserModalComponent);
    modalRef.componentInstance.mode = 'edit';
    modalRef.componentInstance.user = user;
    modalRef.result.then(
      (savedUser) => {
        for (let i = 0; i < this.users.length; i++) {
          if (this.users[i].id === user.id) {
            this.users[i] = savedUser;
          }
        }
      },
      () => {
      }
    );
  }

  handleDeleteClick(user: User) {
    const modalRef = this.modalService.open(UserModalComponent);
    modalRef.componentInstance.mode = 'delete';
    modalRef.componentInstance.user = user;
    modalRef.result.then(
      () => {
        for (let i = 0; i < this.users.length; i++) {
          if (this.users[i].id === user.id) {
            this.users.splice(i, 1);
            break;
          }
        }
      },
      () => {
      }
    );
  }

  displayAccountStatus(user: User): String {
    const accountStatus: string[] = [];
    if (user.enabled) {
      accountStatus.push('Enabled');
    } else {
      accountStatus.push('Disabled');
    }
    if (!user.accountNonExpired) {
      accountStatus.push('Expired');
    }
    if (!user.accountNonLocked) {
      accountStatus.push('Locked');
    }
    if (!user.credentialsNonExpired) {
      accountStatus.push('Credentials Expired');
    }
    return accountStatus.join(', ');
  }

  displayRoles(user: User): string {
    return user.roles.map(item => item.name).join(', ');
  }
}

<div class="card m-2">
  <div class="card-header">Users</div>
  <div class="card-body">
    <button class="btn btn-secondary mb-2" *ngIf="userSessionService.getLoggedInUser().hasRole('ROLE_ADMIN')" (click)="handleAddClick()">Add User</button>
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th class="action-column" *ngIf="userSessionService.getLoggedInUser().hasRole('ROLE_ADMIN')"></th>
          <th class="action-column" *ngIf="userSessionService.getLoggedInUser().hasRole('ROLE_ADMIN')"></th>
          <th>Id</th>
          <th>Username</th>
          <th>Account Status</th>
          <th>Roles</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let user of users">
          <td class="action-column" *ngIf="userSessionService.getLoggedInUser().hasRole('ROLE_ADMIN')">
            <a (click)="handleEditClick(user)">
              <fa-icon [icon]="faPencilAlt"></fa-icon>
            </a>
          </td>
          <td class="action-column" *ngIf="userSessionService.getLoggedInUser().hasRole('ROLE_ADMIN')">
            <a (click)="handleDeleteClick(user)">
              <fa-icon [icon]="faTrashAlt"></fa-icon>
            </a>
          </td>
          <td>{{user.id}}</td>
          <td>{{user.username}}</td>
          <td>{{displayAccountStatus(user)}}</td>
          <td>{{displayRoles(user)}}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// react-ui/src/containers/UserList/UserList.js
import React, {Component}                          from 'react';
import {connect}                                   from 'react-redux';
import {Button, Card, CardBody, CardHeader, Table} from 'reactstrap';
import {FontAwesomeIcon}                           from '@fortawesome/react-fontawesome';

import * as userActions from '../../redux/actions/user';
import UserModal        from '../../components/UserModal';

class UserList extends Component {

  displayAccountStatus = (user) => {
    const accountStatus = [];
    if (user.enabled) {
      accountStatus.push('Enabled');
    } else {
      accountStatus.push('Disabled');
    }
    if (!user.accountNonExpired) {
      accountStatus.push('Expired');
    }
    if (!user.accountNonLocked) {
      accountStatus.push('Locked');
    }
    if (!user.credentialsNonExpired) {
      accountStatus.push('Credentials Expired');
    }
    return accountStatus.join(', ');
  };

  displayRoles = (user) => {
    return user.roles.map(item => item.name).join(', ');
  };

  componentDidMount = () => {
    this.props.loadUsers();
  };

  render() {
    let content;
    if (this.props.loading) {
      content = (<h1>Loading...</h1>);
    } else if (this.props.showError) {
      content = (<h1>Error Loading Users</h1>);
    } else {
      content = (
        <React.Fragment>
          {this.props.isAdmin && <Button
            color="secondary"
            className="mb-2"
            onClick={() => this.props.showModal('Add', {username: ''}, this.props.addUser)}>
            Add User
          </Button>
          }
          <Table striped bordered hover>
            <thead>
              <tr>
                {this.props.isAdmin && <th className="action-column"/>}
                {this.props.isAdmin && <th className="action-column"/>}
                <th>Username</th>
                <th>Account Status</th>
                <th>Roles</th>
              </tr>
            </thead>
            <tbody>
              {this.props.users.map(user => {
                return (
                  <tr key={user.username}>
                    {this.props.isAdmin &&
                    <td className="action-column">
                      <FontAwesomeIcon
                        icon="pencil-alt"
                        onClick={() => this.props.showModal('Edit', user, this.props.editUser)}/>
                    </td>
                    }
                    {this.props.isAdmin &&
                    <td className="action-column">
                      <FontAwesomeIcon
                        icon="trash-alt"
                        onClick={() => this.props.showModal('Delete', user, this.props.deleteUser)}/>
                    </td>
                    }
                    <td>{user.username}</td>
                    <td>{this.displayAccountStatus(user)}</td>
                    <td>{this.displayRoles(user)}</td>
                  </tr>
                );
              })}
            </tbody>
          </Table>
          <UserModal
            open={this.props.modalIsOpen}
            mode={this.props.modalMode}
            user={this.props.selectedUser}
            errorMessage={this.props.modalError}
            submitCallback={this.props.modalSubmitCallback}
            cancelCallback={this.props.hideModal}
          />
        </React.Fragment>
      );
    }

    return (
      <Card className="UserList m-2">
        <CardHeader>Users</CardHeader>
        <CardBody>
          {content}
        </CardBody>
      </Card>
    );
  }
}

const mapStateToProps = (state) => {
  return {
    isAdmin: state.auth.tokenClaims && state.auth.tokenClaims.authorities.indexOf('ROLE_ADMIN') !== -1,
    loading: state.users.loading,
    showError: state.users.showError,
    users: state.users.list,
    selectedUser: state.users.selectedUser,
    modalIsOpen: state.users.modalIsOpen,
    modalMode: state.users.modalMode,
    modalError: state.users.modalError,
    modalSubmitCallback: state.users.modalSubmitCallback
  };
};

const mapDispatchToProps = (dispatch) => {
  return {
    loadUsers: () => dispatch(userActions.loadUsers()),
    showModal: (mode, team, submitCallback) => dispatch(userActions.showUserModal(mode, team, submitCallback)),
    hideModal: () => dispatch(userActions.hideUserModal()),
    addUser: (user) => dispatch(userActions.addUser(user)),
    editUser: (user) => dispatch(userActions.editUser(user)),
    deleteUser: (user) => dispatch(userActions.deleteUser(user))
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(UserList);
